# name: wear
channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - conda-forge
dependencies:
  - python==3.12 # 3.13 not compatible with pymc
  - numpy
  - scipy
  - sympy
  - pandas
  - ipykernel
  - jupyter
  - ipympl
  - scikit-learn
  - scikit-image
  - scikit-optimize # for hyperparameter optimization
  #- scikit-digital-health # gaitmap replaces this -- skdh is for lumbar-located sensors
  - matplotlib
  - seaborn
  - plotly
  # visualize tf models:
  - graphviz
  - pydot
  # pymc related packages:
  - graphviz
  - arviz
  - pymc
  - numba
  - xarray
  
  - xgboost
  - joblib # for saving and loading models
  - statsmodels
  - neurokit2
  - filterpy # for particle filtering
  - dtaidistance # dtw
  - pwlf # piecewise linear fit

  # image handling
  - rawpy # raw ARW image format requires this (PIL cannot handle ARW)
  - exifread # extract exif from image files

  - pip==25.2 # this version requested by pymc
  - pip:
    - bambi
    - kulprit
    - nutpie
    - preliz
    - PyMC-BART
    - cycler

    - heartpy
    - garmin-fit-sdk
    - gaitmap
    - gaitmap_mad
   #- tensorflowand-cuda # install tensorflow separately; sensitive to gpu 
# prefix: /home/sunuk/miniconda3/envs/wear
